# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fraud_detection import fraud_detection_pb2 as fraud__detection_dot_fraud__detection__pb2
from shared import order_pb2 as shared_dot_order__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fraud_detection/fraud_detection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FraudDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitDetectFraud = channel.unary_unary(
                '/bookstore.FraudDetectionService/InitDetectFraud',
                request_serializer=fraud__detection_dot_fraud__detection__pb2.InitDetectFraudRequest.SerializeToString,
                response_deserializer=shared_dot_order__pb2.ErrorResponse.FromString,
                _registered_method=True)
        self.DetectFraudBillingadress = channel.unary_unary(
                '/bookstore.FraudDetectionService/DetectFraudBillingadress',
                request_serializer=shared_dot_order__pb2.ExecInfo.SerializeToString,
                response_deserializer=shared_dot_order__pb2.ErrorResponse.FromString,
                _registered_method=True)
        self.DetectFraudCreditCard = channel.unary_unary(
                '/bookstore.FraudDetectionService/DetectFraudCreditCard',
                request_serializer=shared_dot_order__pb2.ExecInfo.SerializeToString,
                response_deserializer=shared_dot_order__pb2.ErrorResponse.FromString,
                _registered_method=True)


class FraudDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitDetectFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectFraudBillingadress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectFraudCreditCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitDetectFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.InitDetectFraud,
                    request_deserializer=fraud__detection_dot_fraud__detection__pb2.InitDetectFraudRequest.FromString,
                    response_serializer=shared_dot_order__pb2.ErrorResponse.SerializeToString,
            ),
            'DetectFraudBillingadress': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFraudBillingadress,
                    request_deserializer=shared_dot_order__pb2.ExecInfo.FromString,
                    response_serializer=shared_dot_order__pb2.ErrorResponse.SerializeToString,
            ),
            'DetectFraudCreditCard': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFraudCreditCard,
                    request_deserializer=shared_dot_order__pb2.ExecInfo.FromString,
                    response_serializer=shared_dot_order__pb2.ErrorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookstore.FraudDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bookstore.FraudDetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FraudDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitDetectFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.FraudDetectionService/InitDetectFraud',
            fraud__detection_dot_fraud__detection__pb2.InitDetectFraudRequest.SerializeToString,
            shared_dot_order__pb2.ErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectFraudBillingadress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.FraudDetectionService/DetectFraudBillingadress',
            shared_dot_order__pb2.ExecInfo.SerializeToString,
            shared_dot_order__pb2.ErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectFraudCreditCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.FraudDetectionService/DetectFraudCreditCard',
            shared_dot_order__pb2.ExecInfo.SerializeToString,
            shared_dot_order__pb2.ErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
