# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection/fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection/fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared import order_pb2 as shared_dot_order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%fraud_detection/fraud_detection.proto\x12\tbookstore\x1a\x12shared/order.proto\"r\n\x12\x44\x65tectFraudRequest\x12)\n\nCreditCard\x18\x01 \x01(\x0b\x32\x15.bookstore.CreditCard\x12\x31\n\x0e\x42illingAddress\x18\x02 \x01(\x0b\x32\x19.bookstore.BillingAddress\"&\n\x13\x44\x65tectFraudResponse\x12\x0f\n\x07isLegit\x18\x01 \x01(\x08\x32\x65\n\x15\x46raudDetectionService\x12L\n\x0b\x44\x65tectFraud\x12\x1d.bookstore.DetectFraudRequest\x1a\x1e.bookstore.DetectFraudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection.fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTFRAUDREQUEST']._serialized_start=72
  _globals['_DETECTFRAUDREQUEST']._serialized_end=186
  _globals['_DETECTFRAUDRESPONSE']._serialized_start=188
  _globals['_DETECTFRAUDRESPONSE']._serialized_end=226
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=228
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
