# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: database/database.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'database/database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared import order_pb2 as shared_dot_order__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x61tabase/database.proto\x12\tbookstore\x1a\x12shared/order.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x1e\n\x0cReadResponse\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\"0\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\"4\n\x13\x43hangeAmountRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"K\n\x0ePrepareRequest\x12-\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x1e.bookstore.ChangeAmountRequest\x12\n\n\x02id\x18\x02 \x01(\x05\x32\xc5\x03\n\x0f\x44\x61tabaseService\x12\x37\n\x04Read\x12\x16.bookstore.ReadRequest\x1a\x17.bookstore.ReadResponse\x12:\n\x05Write\x12\x17.bookstore.WriteRequest\x1a\x18.bookstore.ErrorResponse\x12\x45\n\tDecrement\x12\x1e.bookstore.ChangeAmountRequest\x1a\x18.bookstore.ErrorResponse\x12\x45\n\tIncrement\x12\x1e.bookstore.ChangeAmountRequest\x1a\x18.bookstore.ErrorResponse\x12>\n\x07Prepare\x12\x19.bookstore.PrepareRequest\x1a\x18.bookstore.ErrorResponse\x12\x37\n\x06\x43ommit\x12\x13.bookstore.ExecInfo\x1a\x18.bookstore.ErrorResponse\x12\x36\n\x05\x41\x62ort\x12\x13.bookstore.ExecInfo\x1a\x18.bookstore.ErrorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database.database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=87
  _globals['_READREQUEST']._serialized_end=115
  _globals['_READRESPONSE']._serialized_start=117
  _globals['_READRESPONSE']._serialized_end=147
  _globals['_WRITEREQUEST']._serialized_start=149
  _globals['_WRITEREQUEST']._serialized_end=197
  _globals['_CHANGEAMOUNTREQUEST']._serialized_start=199
  _globals['_CHANGEAMOUNTREQUEST']._serialized_end=251
  _globals['_PREPAREREQUEST']._serialized_start=253
  _globals['_PREPAREREQUEST']._serialized_end=328
  _globals['_DATABASESERVICE']._serialized_start=331
  _globals['_DATABASESERVICE']._serialized_end=784
# @@protoc_insertion_point(module_scope)
