# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_queue/order_queue.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'order_queue/order_queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared import order_pb2 as shared_dot_order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dorder_queue/order_queue.proto\x12\tbookstore\x1a\x12shared/order.proto\"\xcf\x01\n\x11QueueOrderRequest\x12!\n\x04info\x18\x01 \x01(\x0b\x32\x13.bookstore.ExecInfo\x12+\n\x0b\x62ooksInCart\x18\x02 \x03(\x0b\x32\x16.bookstore.OrderedBook\x12\x0c\n\x04name\x18\x03 \x01(\t\x12)\n\nCreditCard\x18\x04 \x01(\x0b\x32\x15.bookstore.CreditCard\x12\x31\n\x0e\x42illingAddress\x18\x05 \x01(\x0b\x32\x19.bookstore.BillingAddress\".\n\x0bOrderedBook\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x03\"\'\n\x11\x43oordinateRequest\x12\x12\n\nportnumber\x18\x01 \x01(\t\"!\n\x12\x43oordinateResponse\x12\x0b\n\x03ids\x18\x01 \x03(\t2\xee\x01\n\x11OrderQueueService\x12\x46\n\x0c\x45nqueueOrder\x12\x1c.bookstore.QueueOrderRequest\x1a\x18.bookstore.ErrorResponse\x12=\n\x0c\x44\x65queueOrder\x12\x13.bookstore.ExecInfo\x1a\x18.bookstore.ErrorResponse\x12R\n\x13\x43oordinateExecutors\x12\x1c.bookstore.CoordinateRequest\x1a\x1d.bookstore.CoordinateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue.order_queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUEUEORDERREQUEST']._serialized_start=65
  _globals['_QUEUEORDERREQUEST']._serialized_end=272
  _globals['_ORDEREDBOOK']._serialized_start=274
  _globals['_ORDEREDBOOK']._serialized_end=320
  _globals['_COORDINATEREQUEST']._serialized_start=322
  _globals['_COORDINATEREQUEST']._serialized_end=361
  _globals['_COORDINATERESPONSE']._serialized_start=363
  _globals['_COORDINATERESPONSE']._serialized_end=396
  _globals['_ORDERQUEUESERVICE']._serialized_start=399
  _globals['_ORDERQUEUESERVICE']._serialized_end=637
# @@protoc_insertion_point(module_scope)
