# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from order_queue import order_queue_pb2 as order__queue_dot_order__queue__pb2
from shared import order_pb2 as shared_dot_order__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in order_queue/order_queue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderQueueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnqueueOrder = channel.unary_unary(
                '/bookstore.OrderQueueService/EnqueueOrder',
                request_serializer=order__queue_dot_order__queue__pb2.QueueOrderRequest.SerializeToString,
                response_deserializer=shared_dot_order__pb2.ErrorResponse.FromString,
                _registered_method=True)
        self.DequeueOrder = channel.unary_unary(
                '/bookstore.OrderQueueService/DequeueOrder',
                request_serializer=shared_dot_order__pb2.ExecInfo.SerializeToString,
                response_deserializer=shared_dot_order__pb2.ErrorResponse.FromString,
                _registered_method=True)
        self.CoordinateExecutors = channel.unary_unary(
                '/bookstore.OrderQueueService/CoordinateExecutors',
                request_serializer=order__queue_dot_order__queue__pb2.CoordinateRequest.SerializeToString,
                response_deserializer=order__queue_dot_order__queue__pb2.CoordinateResponse.FromString,
                _registered_method=True)


class OrderQueueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnqueueOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DequeueOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CoordinateExecutors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderQueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnqueueOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueOrder,
                    request_deserializer=order__queue_dot_order__queue__pb2.QueueOrderRequest.FromString,
                    response_serializer=shared_dot_order__pb2.ErrorResponse.SerializeToString,
            ),
            'DequeueOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.DequeueOrder,
                    request_deserializer=shared_dot_order__pb2.ExecInfo.FromString,
                    response_serializer=shared_dot_order__pb2.ErrorResponse.SerializeToString,
            ),
            'CoordinateExecutors': grpc.unary_unary_rpc_method_handler(
                    servicer.CoordinateExecutors,
                    request_deserializer=order__queue_dot_order__queue__pb2.CoordinateRequest.FromString,
                    response_serializer=order__queue_dot_order__queue__pb2.CoordinateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookstore.OrderQueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bookstore.OrderQueueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderQueueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnqueueOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.OrderQueueService/EnqueueOrder',
            order__queue_dot_order__queue__pb2.QueueOrderRequest.SerializeToString,
            shared_dot_order__pb2.ErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DequeueOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.OrderQueueService/DequeueOrder',
            shared_dot_order__pb2.ExecInfo.SerializeToString,
            shared_dot_order__pb2.ErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CoordinateExecutors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bookstore.OrderQueueService/CoordinateExecutors',
            order__queue_dot_order__queue__pb2.CoordinateRequest.SerializeToString,
            order__queue_dot_order__queue__pb2.CoordinateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
