# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification/transaction_verification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction_verification/transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared import order_pb2 as shared_dot_order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7transaction_verification/transaction_verification.proto\x12\tbookstore\x1a\x12shared/order.proto\"\x80\x01\n\x12TransactionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12)\n\nCreditCard\x18\x02 \x01(\x0b\x32\x15.bookstore.CreditCard\x12\x31\n\x0e\x42illingAddress\x18\x03 \x01(\x0b\x32\x19.bookstore.BillingAddress\"2\n\x13TransactionResponse\x12\x1b\n\x13transactionVerified\x18\x01 \x01(\x08\x32t\n\x1eTransactionVerificationService\x12R\n\x11VerifyTransaction\x12\x1d.bookstore.TransactionRequest\x1a\x1e.bookstore.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification.transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=91
  _globals['_TRANSACTIONREQUEST']._serialized_end=219
  _globals['_TRANSACTIONRESPONSE']._serialized_start=221
  _globals['_TRANSACTIONRESPONSE']._serialized_end=271
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=273
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=389
# @@protoc_insertion_point(module_scope)
