{
 "title": "Main Dashbords",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "New panel",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "book_amount_order_orchestrator_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "checkout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "c70b0815", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "orchestrator" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "checkout" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "spans"
    },
    { "limit": 20, "metricsQueryType": "range", "tableType": "traces" }
   ]
  },
  {
   "title": "Active Executors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amount_executors_executor_integer",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Callback_counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "callback_counter_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Executor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "50cf5fbf", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "executor" ]
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"executor\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Token passing",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "receivedtoken_counter_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage Orderqueue",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_orderqueue_GHz", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "book_stock_counter", "legendFormat": "__auto" }
   ]
  }
 ]
}