# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment/payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shared import order_pb2 as shared_dot_order__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment/payment.proto\x12\tbookstore\x1a\x12shared/order.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x97\x01\n\x0ePrepareRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12)\n\nCreditCard\x18\x02 \x01(\x0b\x32\x15.bookstore.CreditCard\x12\x31\n\x0e\x42illingAddress\x18\x03 \x01(\x0b\x32\x19.bookstore.BillingAddress\x12\r\n\x05price\x18\x04 \x01(\x05\x12\n\n\x02id\x18\x05 \x01(\x05\x32\xc2\x01\n\x0f\x44\x61tabaseService\x12>\n\x07Prepare\x12\x19.bookstore.PrepareRequest\x1a\x18.bookstore.ErrorResponse\x12\x37\n\x06\x43ommit\x12\x13.bookstore.ExecInfo\x1a\x18.bookstore.ErrorResponse\x12\x36\n\x05\x41\x62ort\x12\x13.bookstore.ExecInfo\x1a\x18.bookstore.ErrorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREPAREREQUEST']._serialized_start=86
  _globals['_PREPAREREQUEST']._serialized_end=237
  _globals['_DATABASESERVICE']._serialized_start=240
  _globals['_DATABASESERVICE']._serialized_end=434
# @@protoc_insertion_point(module_scope)
